language: csharp
solution: Reducto.Sample-CI.sln
install:
    - nuget restore Reducto.Sample-CI.sln
    - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
    - xbuild /p:Configuration=Release Reducto.Sample-CI.sln
    - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/Reducto.Sample.Tests/bin/Release/Reducto.Sample.Tests.dll